// import Header from './components/Header'
import Provider from './components/Provider'
import './globals.css'
// import Provider from '@components/Provider'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={roboto.className}>
        {/* <Provider> */}
        {/* <Header></Header> */}
        {children}
        {/* <h1>footer</h1> */}
        {/* </Provider> */}

      </body>

    </html>
  )
}
